### PR TITLE
Add X7 to supported radios page.

### PR DESCRIPTION
**Pull request by RCdiy**
I'll also add horus is this one is accepted.

### CODE REVIEW

**Comment by bsongis** [comment]
@mhotar I let you decide

**Comment by mhotar** [comment]
I am happy someone took it. I like it, thank you @RCdiy

**Comment by RCdiy** [comment]
@mhotar you are welcome. Once this is accepted I'll do the horus.

**Comment by bsongis** [comment]
Thanks @RCdiy  !

**Comment by schwabe** [comment]
If you are bored you can also add AR9X/ARUNI :)

**Comment by RCdiy** [comment]
@schwabe could you give me a few description lines following the same style as the other board descriptions?

**Comment by RCdiy** [comment]
Does it make sense to group all the diy boards at the bottom? Group transmitters by brand & price? It appears that additions have been sequential. Happy to leave it alone. Just thought I'd ask.

**Pull request merged**
